export const GET_ALL_EXAMS="GET_ALL_EXAMS";

export const PUBLISH_EXAM_REQUEST="PUBLISH_EXAM_REQUEST";
export const PUBLISH_EXAM_SUCCESS="PUBLISH_EXAM_SUCCESS";
export const PUBLISH_EXAM_FAIL="PUBLISH_EXAM_FAIL";

export const GET_EXAM_DETAIL="GET_EXAM_DETAIL";
export const GET_EXAM_QUESTIONS="GET_EXAM_QUESTIONS";
export const GET_EXAM_INSTRUCTIONS="GET_EXAM_INSTRUCTIONS";

export const GET_EXAM_REQUEST="GET_EXAM_REQUEST";
export const GET_EXAM_SUCCESS="GET_EXAM_SUCCESS";
export const GET_EXAM_FAIL="GET_EXAM_FAIL";

