export const GET_ALL_INTERVIEWS_FAIL = 'GET_ALL_INTERVIEWS_FAIL';
export const GET_ALL_INTERVIEWS_REQUEST = 'GET_ALL_INTERVIEWS_REQUEST';
export const GET_ALL_INTERVIEWS_SUCCESS = 'GET_ALL_INTERVIEWS_SUCCESS';